# Get all tags
GET http://localhost:3000/api/tags HTTP/1.1

###

# Get tag by Id

GET http://localhost:3000/api/tags/39614113-7ad5-45b6-8093-06455437e1e2 HTTP/1.1

###

# Create a new tag
POST http://localhost:3000/api/tags HTTP/1.1
Content-Type: application/json

{
  "title": "Журналы"
}

###

# Delete a tag by id

DELETE http://localhost:3000/api/tags/3ee2cc3b-81cc-4789-bb50-d20b73ec2c34 HTTP/1.1

###

# Update a tag by id

PATCH http://localhost:3000/api/tags/f39ed0ab-5129-4984-bd69-2ca375b55605 HTTP/1.1
Content-Type: application/json

{
  "title": "This is new title"
}

###
